"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { BrainCircuit, TrendingDown, TrendingUp, Activity, Sparkles, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { AIReportModal } from "./ai-report-modal"
import { SmartSuggestions } from "./smart-suggestions"

export function InsightsDashboard() {
  const [summaryData, setSummaryData] = useState<any>(null)
  const [predictionData, setPredictionData] = useState<any>(null)
  const [loading, setLoading] = useState({ summary: true, prediction: true })

  const fetchSummary = async () => {
    setLoading(prev => ({ ...prev, summary: true }))
    try {
      const res = await fetch("/api/ai/summary")
      const data = await res.json()
      setSummaryData(data)
    } finally {
      setLoading(prev => ({ ...prev, summary: false }))
    }
  }

  const fetchPrediction = async () => {
    setLoading(prev => ({ ...prev, prediction: true }))
    try {
      const res = await fetch("/api/ai/prediction")
      const data = await res.json()
      setPredictionData(data)
    } finally {
      setLoading(prev => ({ ...prev, prediction: false }))
    }
  }

  useEffect(() => {
    fetchSummary()
    fetchPrediction()
  }, [])

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-slate-800 flex items-center gap-2">
            <BrainCircuit className="h-8 w-8 text-indigo-600" />
            AI Intelligence
          </h2>
          <p className="text-slate-500 mt-1">Deep analysis and predictions based on your footprint trends.</p>
        </div>
        <div className="flex gap-2 w-full md:w-auto">
          <Button variant="outline" onClick={() => { fetchSummary(); fetchPrediction(); }}>
            <RefreshCw className="mr-2 h-4 w-4" /> Refresh Insights
          </Button>
          <AIReportModal />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="md:col-span-2 border-indigo-100 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-3 opacity-10">
            <Sparkles className="w-24 h-24 text-indigo-600" />
          </div>
          <CardHeader>
            <CardTitle className="text-xl text-indigo-900">Weekly Narrative Summary</CardTitle>
            <CardDescription>Generated by Claude</CardDescription>
          </CardHeader>
          <CardContent>
            {loading.summary ? (
              <div className="space-y-2 animate-pulse">
                <div className="h-4 bg-slate-200 rounded w-full"></div>
                <div className="h-4 bg-slate-200 rounded w-5/6"></div>
                <div className="h-4 bg-slate-200 rounded w-4/6"></div>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-lg leading-relaxed text-slate-700 font-medium">
                  {summaryData?.summary || "Add more data to generate a weekly summary."}
                </p>
                {summaryData?.roastOrPraise && (
                  <div className="mt-4 p-4 bg-slate-50 border-l-4 border-indigo-400 rounded-r text-slate-600 italic">
                    "{summaryData.roastOrPraise}"
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="shadow-sm border-slate-100">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-slate-800">
              <Activity className="h-5 w-5 text-blue-500" />
              30-Day Forecast
            </CardTitle>
          </CardHeader>
          <CardContent>
            {loading.prediction ? (
              <div className="flex justify-center items-center py-8">
                <span className="animate-pulse text-slate-400">Predicting...</span>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center text-center space-y-4">
                <div className="flex items-center gap-2">
                  <span className="text-4xl font-bold text-slate-800">
                    {predictionData?.predictedTotal ? Math.round(predictionData.predictedTotal) : 0}
                  </span>
                  <span className="text-lg text-slate-500 font-medium">kg CO2</span>
                </div>
                
                <div className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-bold ${
                  predictionData?.trend === 'down' ? 'bg-emerald-100 text-emerald-700' :
                  predictionData?.trend === 'up' ? 'bg-red-100 text-red-700' :
                  'bg-amber-100 text-amber-700'
                }`}>
                  {predictionData?.trend === 'down' && <TrendingDown className="h-4 w-4 mr-1" />}
                  {predictionData?.trend === 'up' && <TrendingUp className="h-4 w-4 mr-1" />}
                  {predictionData?.trend === 'stable' && <RefreshCw className="h-4 w-4 mr-1" />}
                  Trend: {predictionData?.trend?.toUpperCase()}
                </div>
                
                <p className="text-sm text-slate-500 max-w-xs">{predictionData?.reasoning}</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <div>
        <h3 className="text-xl font-semibold mb-4 text-slate-800">Actionable Tips</h3>
        <SmartSuggestions />
        <SmartSuggestions />
      </div>
    </div>
  )
}
